{{ $r := include "azs.array" . }}
{{- range (split "," $r) }}
---
{{if $.Values.autoscaling.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  {{if ne . "" }}
  name: {{ include "affinit-with-the-canary.fullname" $ }}-{{ . }}
  {{else}}
  name: {{ include "affinit-with-the-canary.fullname" $ }}
  {{end}}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    {{if ne . "" }}
    name: {{ include "affinit-with-the-canary.fullname" $ }}-{{ . }}
    {{else}}
    name: {{ include "affinit-with-the-canary.fullname" $ }}
    {{end}}
  minReplicas: {{ $.Values.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ $.Values.autoscaling.hpa.maxReplicas }}
  metrics:
{{ toYaml $.Values.autoscaling.hpa.metrics| indent 2 }}
{{end}}
{{- end }}
