# Default values for affinit-with-the-canary.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: firesh/nginx-lua
  tag: alpine
  pullPolicy: IfNotPresent

env:
  # baseSvcUrl: ""
  stableSvcName: kubeapp-production-service
  canarySvcName: kubeapp-canary-service
  stableSvcPort: "80"
  canarySvcPort: "80"
  canaryWeight: "0.5"
  cookieMaxAge: "172800"
  cookieName: "cn"
  cookieEnabled: "true"

nameOverride: ""
fullnameOverride: ""

service:
  name: nginxcan-service
  type: ClusterIP
  port: 80

autoscaling:
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 4
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 65
    - type: Resource
      resource:
        name: memory
        targetAverageValue: 700Mi

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 150m
   memory: 200Mi
  requests:
   cpu: 100m
   memory: 128Mi

# True to apply a rolling update strategy, false for default
rollingUpdate:
  enabled: false
