# Default values for affinit-with-the-canary.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: firesh/nginx-lua
  tag: alpine
  pullPolicy: IfNotPresent

env:
  # baseSvcUrl: ""
  stableSvcName: kubeapp-production-service
  canarySvcName: kubeapp-canary-service
  stableSvcPort: "80"
  canarySvcPort: "80"
  canaryWeight: "0.5"
  cookieMaxAge: "172800"
  cookieName: "cn"
  cookieEnabled: "true"

nameOverride: ""
fullnameOverride: ""

service:
  name: nginxcan-service
  type: ClusterIP
  port: 80

autoscaling:
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 4
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 65
    - type: Resource
      resource:
        name: memory
        targetAverageValue: 10Mi

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 10m
   memory: 15Mi
  requests:
   cpu: 5m
   memory: 6Mi

# True to apply a rolling update strategy, false for default
rollingUpdate:
  enabled: false

# Format for logs
logging:
  custom: true
  customFormat: |
    log_format main '{ "time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x-forward-for": "$proxy_add_x_forwarded_for", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time, "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent"}';

# Enable availability zones even pod distribution
azs:
  enabled: false
  values:
    - us-east-1a
    - us-east-1b

# Add annotations in case you need
setAnnotations: false
# annotations: {}


# Stub status
# For get metrics in the endpoint /nginx_status
# This is useful when you try to get metrics from an agent (i.e. datadog)
stubStatus:
  enabled: false
