apiVersion: v1
appVersion: "1.1"
description: To build a simple way of deploy some kind of canary with a consistent user experience on top of Kubernetes.
name: affinitwiththecanary
version: 0.1.3
keywords:
  - canary
  - deployment
home: https://github.com/juanmatias/affinity-with-the-canary
maintainers:
  - name: Juan Matias Kungfu de la Camara Beovide
    email: juan.delacamara@3xmgroup.com
    url: http://juanmatiasdelacamara.wordpress.com
